### ISSUE TITLE
Watch 'n' build

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/DocumenterTools.jl#13]
Originally in JuliaDocs/Documenter.jl#11, but I think DocumenterTools would be more appropriate for this. Some nice wrapper around Revise probably (ref JuliaDocs/Documenter.jl#828).

**Comment by simonbyrne** [comment]
Functionality provided in https://github.com/tlienart/LiveServer.jl#serve-docs

**Comment by mortenpi** [comment]
Watching docstrings with LiveServer is tracked in https://github.com/tlienart/LiveServer.jl/issues/140
