### ISSUE TITLE
DocumenterTools in Documenter

### ISSUE THREAD

**Issue by Marco-Congedo** [JuliaDocs/DocumenterTools.jl#23]
Hello,

  maybe a naif question:
why DocumenterTools is not embedded in Documenter?

**Comment by mortenpi** [comment]
It's mainly to keep Documenter, which is installed on CI VMs, when building Julia from source etc., as lightweight as reasonably possible. The main concern is dependecies. So all non-essential functionality we can put in DocumenterTools with whatever dependencies we want.

**Comment by Marco-Congedo** [comment]
OK, thanks
