### ISSUE TITLE
Keygen.jl as a separate package

### ISSUE THREAD

**Issue by aminya** [JuliaDocs/DocumenterTools.jl#37]
Keygen.jl can be used in various situations that are not limited to Documenter. For example, many GitHub actions need tokens.

Related: https://github.com/JuliaDocs/DocumenterTools.jl/issues/36

**Comment by mortenpi** [comment]
No objections from me if someone wants to borrow the code from here to fork it out into a separate package.

**Comment by mortenpi** [comment]
I just found this PR to get OpenSSH into Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/669

**Comment by giordano** [comment]
[`OpenSSH_jll`](https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl) is now a thing
