### ISSUE TITLE
Fix Travis.genkeys() for Windows

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/DocumenterTools.jl#5]
Refs: JuliaDocs/Documenter.jl#767 JuliaDocs/Documenter.jl#761

**Comment by Datseris** [comment]
bump, please :)

**Comment by mortenpi** [comment]
It's very much up for grabs :slightly_smiling_face: It shouldn't be too hard to port @zundertj's solution in JuliaDocs/Documenter.jl#767 to here.

**Comment by ViralBShah** [comment]
Close?

**Comment by Datseris** [comment]
Yes. Things work perfectly fine now with the GitHub actions integration.
