### ISSUE TITLE
Allow OpenSSH @9

### ISSUE THREAD

**Issue by eschnett** [JuliaDocs/DocumenterTools.jl#73]
OpenSSH @8, the currently required version, requires OpenSSL @1. Thus DocumenterTools is currently holding up many package upgrades that switch to OpenSSL @3. Note that OpenSSL @1 will become unsupported this fall.

Is there a particular reason that OpenSSH @8 is required?

**Comment by mortenpi** [comment]
OpenSSH 9 should probably be fine. I assume the `ssh-keygen` CLI is compatible. Should just double check that `genkeys` still produces a reasonable output.

The PR is against the wrong repository though.

**Comment by eschnett** [comment]
> The PR is against the wrong repository though.

How silly of me. Corrected via https://github.com/JuliaDocs/DocumenterTools.jl/pull/74.
