### ISSUE TITLE
Using development version of Documenter.jl will pull old release of DocumenterTools

### ISSUE THREAD

**Issue by frankier** [JuliaDocs/DocumenterTools.jl#79]
It looks like DocumenterTools.jl 0.1.2 did not require Documenter. What this means is that if we attempt to `add DocumenterTools` alongside a development release of Documenter (which has had its version incremented to 0.28), the newest version of this package is not installed, and instead 0.1.2 is.

This is the case when I try to build the Documenter docs locally.

One possible fix would be to not increment Documenter.jl version numbers until a release is made. I'm not sure about the pros and cons of this, but I believe this is the version incrementing pattern I have come across most frequently in the Julia ecosystem.

I have currently worked around it by using `dev` to install a local working copy of this repo with 0.28 added to its compat bounds.

**Comment by mortenpi** [comment]
If you run the `./docs/instantiate.jl` script, it will instantiate the correct environment. I've created special tags that are compatible with Documenter#master: https://github.com/JuliaDocs/DocumenterTools.jl/tree/documenter-v0.1.17+0.28.0-DEV

**Comment by frankier** [comment]
All makes sense. I think I'll close this since there's nothing to action here.
