### ISSUE TITLE
Compat helper is disabled

### ISSUE THREAD

**Issue by hyrodium** [JuliaDocs/DocumenterTools.jl#87]
![image](https://github.com/JuliaDocs/DocumenterTools.jl/assets/7488140/40dad2ce-854a-4a38-833b-e47d720aff48)

https://github.com/JuliaDocs/DocumenterTools.jl/actions/workflows/CompatHelper.yml

**Comment by mortenpi** [comment]
Good catch. Re-enabled it now. Thanks!
